### ISSUE TITLE
Accounting in retrieval

### ISSUE THREAD

**Issue by ralph-pichler** [ethersphere/bee#415]
# Task

As a first step we want to implement `Accounting` for `retrieval` without settlement taking place.

- [x] Settle on `Accounting` interface
- [x] ~~Migrate `int256` package from `swarm` if necessary.~~ (do accounting with int64s)
- [x] Mock implementation for `Accounting` that can be used in tests. All functions can be no-ops.
- [x] Keep track of balances
  - [x] Adjust balances in `Add`
  - [x] Persist balances (on every update)
- [x] Integrate `Accounting` with `retrieval` protocol (with a fixed price per chunk and po).
  - [x] Call `Accounting` in `retrieveChunk`
  - [x] Call `Accounting` in the handler
  - [x] Implement suitable fixed pricing strategy
  - [x] Wrap into a disconnecting error if error in `.Add`
- [ ] Expose APIs to query balances
  - [ ] get balance with 1 peer
  - [ ] get all balances with all peers
- [x] Expose metrics related to `Accounting` (probably should be total credited, total debited or something)
- [x] Enable accounting by default
  - [x] Ensure that we actually want to do this
  - [x] Strategy to deal with non-accounting nodes (=how to avoid imbalance later)
  - [x] ~~Enable in `node.go` with high disconnect thresholds~~ (configurable with high default)

A possible `Accounting` interface could be:
```go
type Interface interface {
	// Reserve reserves a portion of the balance for peer
	Reserve(peer swarm.Address, price uint64) error
	// Release releases reserved funds
	Release(peer swarm.Address, price uint64)
	// Credit the peer with the given price
	Credit(peer swarm.Address, price uint64) error
	// Debit the peer with the given price
	Debit(peer swarm.Address, price uint64) error
}
```

## Acceptance criterea

- Accounting takes place on retrieval requests and this can be observed using the APIs or metrics.

**Comment by Eknir** [comment]
Congrats all on successfully finishing this issue.
