### ISSUE TITLE
Payment threshold and disconnects

### ISSUE THREAD

**Issue by ralph-pichler** [ethersphere/bee#417]
# Task

Instruct settlement to do a payment if threshold is met. Disconnect if disconnect threshold is exceeded. A mock settlement layer can be used here.

- [x] `Settlement` interface with a mock implementation where settlement always works
  - [x] Create a simple protocol with a pay message containing the value
  - [x] Adjust accounting balance on received pay message
- [x] Introduce accounting/pricing protocol
  - [x] Communicate payment threshold to connected peers
  - [x] Introduce per-peer payment threshold (their threshold)
  - [x] Adjust peers payment threshold on received message
- [x] Changes to `Accounting`
  - [x] Introduce a fixed payment threshold (for now)
  - [x] Call `Settlement` if payment threshold exceeded or if we are close (depends on details of `Reserve`)
  - [x] Adjust `Reserve` to work with peers payment threshold
  - [x] Return error in `Add` if disconnect threshold is met
  - [x] Instead of configurable disconnect threshold, use payment treshold plus tolerance

## Acceptance criterea

Peers exchange payment threshold and pay each other with fake payment to restore balance.
