### ISSUE TITLE
Global Pinning Phase 0

### ISSUE THREAD

**Issue by santicomp2014** [ethersphere/bee#440]
Tasks for global pinning, port from Swarm to BEE
Initial porting process, barebones for this phase 0

## Tasks
- [x]  Trojan chunk implementation porting as a standalone package in bee
- [x]  take targets as arguments in download path
- [x]  logic to detect chunk as missing
- [x]  send a trojan chunk 
- [x]  inspect Bee project to find possible integration places
- [x]  create integration test issue for @svetomir
- [x]  plan with @zelig and @nolash PSS porting

## PRs
| # | title  | status  |
|---|---|---|
| #429 | Trojan chunk support | **closed** |
| #430 | Add targets to query param on download path | **closed** |
| #466 | PSS | **closed** |
| #479 | Chunk repair | **closed** |
| #556 | remove chunk debug API | **closed** |
| #453 | Integration test | **issue created** |

**Comment by Eknir** [comment]
Hi guys, what is the status of this one?

**Comment by jmozah** [comment]
It is done. We just have to merge. I need to check if i need to wait and merge in master or merge it right no in global-pinin-pss branch itself.

**Comment by acud** [comment]
looks like done
