### ISSUE TITLE
Global Pinning Phase 1

### ISSUE THREAD

**Issue by santicomp2014** [ethersphere/bee#441]
Tasks for global pinning, port from Swarm to BEE
This phase consists

## Tasks
- [ ]  Mine and send to pinners
- [ ]  Identification of chunk as trojan and sending to chunk repair module
- [ ]  decode trojan and repair the chunk by sending the missing chunk to n/w
- [ ]  parallelize minning for trojan chunk
- [x]  integrate PSS into BEE

## PRs
| # | title  | status  |
|---|---|---|
| #466 | pss port from Swarm | **merged** |

**Comment by Eknir** [comment]
Is this done @santicomp2014 ? If so: could you update Zenhub? If not, could you mention what needs to be done? Generally, would appreciate updated issues, given that you guys have achieved a good milestone!
