### ISSUE TITLE
Kademlia connectivity

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#47]
# Epic

Divided into 3 phases:
- [ ] phase 0 - basic kademlia implementation - depth calculation and connection management
- [ ] phase 1 - wire in kademlia to be used by the node by default (including all protocols)
- [ ] phase 2 - choose protocol and implement scoring function

## Story

As a user of Swarm, I don't want to connect to all online Swarm nodes, but still maintain the possibility to reach all online nodes, such that I can manage my peer connections more efficiently.

## Background

[Kademlia Connectivity](https://pdos.csail.mit.edu/~petar/papers/maymounkov-kademlia-lncs.pdf)

Tasks:
- [x] introduce notion of depth
- [x] create separate test vectors for `pslice` type
- [x] plug disconnection notification from peer registry to topology + tests
- [x] JSON API kademlia representation
- [x] Human consumable table format representation _(I've settled for `json.MarshalIndent` for now...)_
- [x] bootstrapping and connectivity maintenance:
- - [x] add peers to kademlia but not necessarily connect to them directly
- - [x] ~~sync.Cond for new (known but unconnected) peers? but also for when a peer disconnects~~
- - [x] worker goroutine to choose what to do with new peers added
- - [x] ~~mark and sweep when depth changes~~
- - [x] ~~short-circuit initial connections to build topology faster(not sure about this one)~~
