### ISSUE TITLE
Upload syncs to closest node

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#48]
# Epic

## Story

As a user of Swarm, I want that my chunk is stored at the node whose address is closest to the address of the chunk, such that anybody who requests the chunk afterwards, knows where to find this chunk.

### Full connectivity
This epic can be fulfilled on a full-connectivity network. The node who uploads a chunk looks in his address book for the node whose address is closest to the address of the chunk. In a full connectivity network, this happens to be the node who is closest to the address of the chunk. In a partial connectivity network (i.e. Kademlia), this may or may not be the node who is closest to the address of the chunk. From the perspective of the node, however, this doesn't matter. He just forwards the push sync request to the connected node who is closest to the address of the chunk.

### Note on pricing
For this epic, it will be sufficient to upload the chunk to the closest connected node. However, in the future, there might be a possibility where the closest connected node is not the node to whom we should forward the push-sync, if there is a node who is further away, but cheaper. 

See (picture from BOS):
![image](https://user-images.githubusercontent.com/33000441/78660668-ca8ba680-78cd-11ea-894d-ee0c8431167f.png)

## Acceptance criteria
- In a network with full connectivity, 100 random chunks are uploaded, and every chunk is stored only at the node whose address is closest to the chunks address

## Dependencies
- [x] Modify topology driver interface to have a `SyncPeer` method
- [x] Modify full topology driver implementation to return closest peer for `SyncPeer`
- [x] Create protocol boilerplate
- [ ] Protocol sinks chunks from two sources - push sync localstore subscription and chunks coming from the network on the same protocol

Protocol test vectors:
- [x] make sure chunk gets picked up from localstore push index and gets sent to the closest peer
- [x] forwarding test - incoming message with chunk, check if there's a closer peer (there is, or maybe there is not) - forward to that peer
- [ ] no forwarding test - check that node does not forward when it is the closest (handle `toplogy.ErrWantSelf`)
