### ISSUE TITLE
Storage incentives architecture proposals

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#654]
Several architectural proposals need to be defined 
background here:

 architecture proposals by scope
- [x] upload with postage stamp - https://hackmd.io/rYze0NZ5Ryi2HNmc62ogWA
- [x] stamping chunks during upload https://hackmd.io/k42tvB44RWGXtpbpmdcv2g
- [x] sending and validating postage stamps https://hackmd.io/t1uOx-URTyyVhqnGxBv5xA
- [x] postage stamps in the localstore - garbage collection based on postage value https://hackmd.io/2NgPR2CeQICKzWBAH7Mk0Q#
- [x]  postage smart contracts - https://hackmd.io/tvacCgfBSWmeConc3rFOtw
- [x] Postage API https://hackmd.io/XE6CATOkTki3AM9QcHXjvg?both

related - need to filter?
- - https://hackmd.io/2NgPR2CeQICKzWBAH7Mk0Q#
- - https://github.com/ethersphere/swarm/pull/2077
- - https://github.com/ethersphere/swarm/pull/1352
- - https://github.com/ethersphere/swarm/issues/2035
- - https://github.com/ethersphere/swarm/issues/1031
- - https://github.com/ethersphere/swarm/issues/1017
- - https://github.com/ethersphere/swarm/issues/757

**Comment by Eknir** [comment]
Rinke: https://hackmd.io/tGDj78znQeyrk1wI34Ys_w?view
Zelig: https://hackmd.io/2XLZhMUfTbuhWU5pTHR6gg?view

**Comment by Eknir** [comment]
@zelig, could you please outline here the areas that need an architecture proposal for the first phase of storage incentives (with on-chain oracle). I see that this issue contains references to the raffle, which must be removed.

**Comment by Eknir** [comment]
Link to hackmd (per sprint planning meeting)
https://hackmd.io/rYze0NZ5Ryi2HNmc62ogWA

**Comment by acud** [comment]
this is done
