### ISSUE TITLE
Swap settlement and chequebook integration

### ISSUE THREAD

**Issue by ralph-pichler** [ethersphere/bee#656]
# Task

Implement swap chequebook as a settlement layer.

* [x] Introduce a swap settlement protocol to exchange cheques
* [x] Introduce a swap `Settlement` implementation
  * [x] signs and stores cheques and sends them when payment is required
  * [x] notifies accounting after receiving and verifying cheque
  * [x] verify counterparty chequebook on first encounter
  * [x] store received cheques so they can be cashed later
