### ISSUE TITLE
Deploy and fund chequebook on first startup

### ISSUE THREAD

**Issue by ralph-pichler** [ethersphere/bee#659]
# Task

A swap chequebook needs to be deployed on startup if one already does not already exist.

- [x] Integrate `go-sw3` library with bee.
- [x] Add a cli options to specify eth endpoint and factory address
- [x] On startup check if chequebook address already in store
  - [x] if not, deploy one with the factory and store that address
  - [x] flag to not do this (zero eth entry), or pass existing chequebook address
  - [x] prefund chequebook with tokens
  - [x] if there is a chequebook verify that instead
