### ISSUE TITLE
Upload with postage batch

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#687]
As a user I'd like to be able to be able to attach a postage stamp to my upload to Swarm.
I would like to attach the postage stamp in a form of an HTTP header to the upload.

Scope of work:
- [ ] HTTP API changes
- [ ] Underlying type changes (shed, chunk, new postage stamp type)
- [ ] Hashing pipeline changes
- [ ] Mock Stamper changes

**Comment by Eknir** [comment]
@acud , I would argue that this is not the user story. A user doesn't want to pay--he wants to have the certainty that his content is not pushed out by less relevant content. I suggest to update this user story to:

"As a user of Swarm, I want to signal how much I value uploading a chunk, such that my chunk won't be garbage-collected due to lower-value chunks"

Please update if you agree.

**Comment by Eknir** [comment]
The title should be changed to signal value of chunks

**Comment by Eknir** [comment]
Another user story (from the storer-perspective): 

As a storer node with capacity pressure, I want to garbage-collect those chunks which are worth least to the uploader, such that my storage space generates the biggest value for the users of Swarm.

**Comment by acud** [comment]
I narrowed the scope of this epic so that it is actually achievable within a sprint or two. I dont want to include blockchain interaction here, no smart contract or anything, not even validation. Just upload changes as we discussed in the proposal. If this is not good enough then please feel free to change it however you'd like.

**Comment by Eknir** [comment]
@acud , the PR that is connected with this issue is merged. Is the issue done?

**Comment by Eknir** [comment]
If so, please drag it to the appropriate column in the review workspace
