### ISSUE TITLE
setup goerli network for release

### ISSUE THREAD

**Issue by ralph-pichler** [ethersphere/bee#723]
# Task

- [x] deploy token and factory
- [x] add factory address default to bee client
- [x] setup a faucet for g-eth and g-bzz

## Acceptance criterea

the bee node automatically uses the correct factory when connected to a goerli node
