### ISSUE TITLE
Make smart contract for postage stamp phase 1

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#850]
Discuss @paxthemax @ralph-pichler @Eknir and @zelig discuss this and update this issue accordingly.

- [x] setup smart contract framework
- [x] setup ci pipeline
- [x] implement the contract with the interface described in https://hackmd.io/tvacCgfBSWmeConc3rFOtw
- [x] add unit tests
- [ ] generate bindings

**Comment by Eknir** [comment]
Hi @ralph-pichler and @paxthemax , thanks for adding the detail to this issue.
I made this issue into an epic, and created issues for each checkbox item which you enumerated here. The reason why I did this, is because I assume that you will be making one PR for each item.. Hence, we can track those PRs, together with the issue. If you guys are making a new repository, we should add that to Zenhub. It should be straightforward to do, but perhaps I am the only one who can do this (?). Let me know if you need help!

**Comment by Eknir** [comment]
@paxthemax @ralph-pichler , could we bring this epic to a conclusion by this sprint? I see that #902 and #905 are still open. At the same time, I spoke with Pavle and he convinced me that we should de-prioritize the automatic generation of the bindings.

Could the two of you please sync on this and decide what should be done this sprint, so that we can say that the smart-contracts are done (for the time being)?

**Comment by Eknir** [comment]
I am putting #902 and #905 in the active sprint, but please consider together the acceptance criteria of both

**Comment by ralph-pichler** [comment]
@Eknir in storage-incentives branch we just copied over the abi and interface with it directly, so we might not need to use go bindings here. I think we can set this to done and create a separate task should the need for them arise.
